version: "3.3"

networks:
  app-network:

volumes:
  dir-site:

services:
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DATABASE}"
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - dir-site:/var/lib/postgresql/data
    networks:
      - app-network
    expose:
      - "${DB_PORT}"
    command: -p ${DB_PORT}
